export const GET_EVENTS = 'GET_EVENTS'
export const GET_TYPES = 'GET_TYPES'
export const PATCH_EVENT = 'PATCH_EVENT'
export const DELETE_EVENT = 'DELETE_EVENT'
export const CREATE_EVENT = 'CREATE_EVENT'
export const SET_GET_ROW = 'SET_GET_ROW'
